### ISSUE TITLE
Confirm correct appeal code is set

### ISSUE THREAD

**Issue by phillipadsmith** [phillipadsmith/support.thetyee.ca#11]
Doesn't look like it's been updated

**Comment by phillipadsmith** [comment]
@MrBryan Confirmed with Jeanette that the appeal code should be set to 'fall2015'

**Comment by MrBryan** [comment]
Is that the "campaign=" parameter on the widget or something else?

**Comment by phillipadsmith** [comment]
It's the code that is manually set in app.pl

Grep for appeal_code in app.pl and you'll see it.

**Comment by MrBryan** [comment]
3a593b5 closed
