### ISSUE TITLE
Media and digital policy line is not like the others: update to match

### ISSUE THREAD

**Issue by phillipadsmith** [phillipadsmith/support.thetyee.ca#12]
@MrBryan Media and digital policy line doesn't look right to me.

**Comment by phillipadsmith** [comment]
Also the Government line (see attached):
<img width="243" alt="time_to_vote_--_the_tyee" src="https://cloud.githubusercontent.com/assets/34128/11350052/7e0ac928-91e4-11e5-95ba-afb9c4ddda39.png">

**Comment by MrBryan** [comment]
fixed 1382883
