### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by phillipadsmith** [phillipadsmith/support.thetyee.ca#25]
From Jeanette:

Also, here are the copy changes to those 2 text tiles so that they look more consistent. All 3 now have roughly the same word count. 'Our Vision' can stay the same, just the other 2 need changes:

How you can help

By contributing to The Tyee on a monthly basis, you are helping to strengthen and grow our team of fierce, tough-minded journalists and editors. Tyee Builders who give every month allow our small and nimble team to plan ahead, and produce original stories that you will not see anywhere else. We don’t put our articles behind paywalls, so your contribution helps to keep our stories open and available to everyone.

Join our community

We want to know which issues matter most to you. Energy and environment? Inequality? Electoral reform? When you sign up, you’ll complete a news priority survey that will help inform our reporting. As a special thanks for joining, you’ll receive editorial reports, discounts from partners, random swag giveaways, and discounts on special events and Tyee Master Classes. Give at the $15/month or higher levels, and get our political paper dolls set, updated for 2015!

**Comment by MrBryan** [comment]
got those already
