### ISSUE TITLE
Update pre-filled Tweet on /share page

### ISSUE THREAD

**Issue by phillipadsmith** [phillipadsmith/support.thetyee.ca#26]
From Jeanette:

Spotted something else that needs changing. Right now the Twitter button on the share page populates this tweet:

The federal election is coming. Join me and help fund more independent reporting from @TheTyee http://support.thetyee.ca/

Can we change to:

I support #indiemedia. Join me and help fund more independent reporting from @TheTyee https://support.thetyee.ca

**Comment by phillipadsmith** [comment]
This should happen before launch.

**Comment by MrBryan** [comment]
did it (before launch) ;)
