### ISSUE TITLE
Uncaught ReferenceError: v is not defined

### ISSUE THREAD

**Issue by phillipadsmith** [phillipadsmith/support.thetyee.ca#27]
Line 65 of widgets.js, FYI. 

Just a test data issue, perhaps...?

**Comment by MrBryan** [comment]
yeah that's because there are no supporters to list through since nobody donated or their anonymous preference wasn't passed on

**Comment by MrBryan** [comment]
could wrap it in a "if supporters" if we want .. i guess it could happen at the start of a campaign

**Comment by phillipadsmith** [comment]
@MrBryan Up to you; just flagging. :)

**Comment by phillipadsmith** [comment]
This should get fixed before launch.

**Comment by MrBryan** [comment]
solved by having some votes for each category
